baseURL = "https://blog.kiodo.io/"
defaultContentLanguage = "en"
disqusShortname = "blog-kiodo-io"
googleanalytics = "UA-121900342-1"
enableEmoji = true
enableRobotsTXT = true
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
pygmentsUseClasses = true
theme = "dream-plus"
themesDir = "../../"
title = "Fabio Chiodini's Blog"
[params]
author = "Fabio Chiodini"
avatar = "https://raw.githubusercontent.com/FabioChiodini/blog.kiodo.it/master/images/ZBackground.jpg"
bgBlur = "0px"
bgImage = "https://raw.githubusercontent.com/FabioChiodini/blog.kiodo.it/master/images/BGIMAGE.jpg"
contentType = "post"
description = "All the stuff that I like: Tech, Cloud Native Applications, Containers, Serverless and what's Next"
enableCategories = true
enableColorBG = false
enableShareCard = true
enableTags = true
enableToc = true
favicon = "/img/defaultFav.ico"
itemsPerPage = 4
motto = "Always be learning!!!"
twitterEmoji = true
[social]
email = ""
github = "FabioChiodini"
medium = ""
linkedin = "fabiochiodini"
siteStartYear = 2018
stackoverflow = ""
twitter = "FabioChiodini"
